import type { Workspace } from "../../../sandbox/cloud/types.js"
import { buildProxyCommand } from "../provisioning/proxy-command.js"

export const MANAGED_HEADER = "# Managed by kimchi — do not edit by hand."
export const MANAGED_FOOTER_HINT = "# Regenerated by `kimchi ssh-config` or when listing workspaces."

const HOST_PREFIX = "kimchi-"

interface RenderedBlock {
	alias: string
	body: string
}

/**
 * Renders the managed ssh_config file body from a workspace list.
 *
 * Workspaces without a provisioned `host` are skipped — there's nothing to
 * connect to until they come up. The output is deterministic (sorted by
 * alias) so unchanged inputs produce byte-identical output and the file
 * doesn't churn between runs.
 */
export function renderSshConfig(workspaces: Workspace[], now: Date = new Date()): string {
	const blocks = renderBlocks(workspaces)
	const header = [MANAGED_HEADER, `# Generated at ${now.toISOString()}.`, MANAGED_FOOTER_HINT].join("\n")

	if (blocks.length === 0) {
		return `${header}\n\n# No provisioned workspaces.\n`
	}

	const body = blocks
		.sort((a, b) => a.alias.localeCompare(b.alias))
		.map((b) => b.body)
		.join("\n\n")
	return `${header}\n\n${body}\n`
}

function renderBlocks(workspaces: Workspace[]): RenderedBlock[] {
	const provisioned = workspaces.filter((w) => typeof w.host === "string" && w.host.length > 0)
	const aliases = assignAliases(provisioned)
	return provisioned.map((ws) => ({
		alias: aliases.get(ws.id) ?? "",
		body: renderBlock(aliases.get(ws.id) ?? "", ws),
	}))
}

function renderBlock(alias: string, ws: Workspace): string {
	const proxyCommand = buildProxyCommand(ws.id)
	const host = ws.host ?? ""
	const lines = [
		`Host ${alias}`,
		`    HostName ${host}`,
		"    User sandbox",
		`    ProxyCommand ${proxyCommand}`,
		"    StrictHostKeyChecking no",
		"    UserKnownHostsFile /dev/null",
		"    LogLevel ERROR",
	]
	return lines.join("\n")
}

/**
 * Assigns a unique alias per workspace. Same name → same slug deterministically;
 * collisions get an `-<id-prefix>` suffix.
 */
function assignAliases(workspaces: Workspace[]): Map<string, string> {
	const slugs = new Map<string, string>()
	for (const ws of workspaces) {
		slugs.set(ws.id, slugify(ws.name) || ws.id.slice(0, 8).toLowerCase())
	}

	const counts = new Map<string, number>()
	for (const slug of slugs.values()) {
		counts.set(slug, (counts.get(slug) ?? 0) + 1)
	}

	const result = new Map<string, string>()
	for (const ws of workspaces) {
		const slug = slugs.get(ws.id) ?? ws.id.slice(0, 8)
		const needsSuffix = (counts.get(slug) ?? 0) > 1
		const idSuffix = ws.id
			.replace(/[^a-z0-9]/gi, "")
			.slice(0, 8)
			.toLowerCase()
		const final = needsSuffix && idSuffix ? `${slug}-${idSuffix}` : slug
		result.set(ws.id, `${HOST_PREFIX}${final}`)
	}
	return result
}

export function slugify(name: string): string {
	return name
		.toLowerCase()
		.normalize("NFKD")
		.replace(/\p{M}/gu, "")
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^-+|-+$/g, "")
}
